### PR TITLE
Merge changes from datagovsg fork

### LINKED ISSUE #113: http://www.w3.org/TR/2001/REC-xml-c14n-20010315
Hello @bjrmatos @yaronn, really need a hand with this. I read all the issues and PR relate to c14n and i am aware it's not supported yet. But perhaps someone could help me to solve this problem because i'm sure it's a namespace or whiterspace canonicalization diference that is bothering. 

``` xml
<Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
<SignedInfo>
  <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
  <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
  <Reference URI="">
    <Transforms>
      <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
      <Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
    </Transforms>
    <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
    <DigestValue>txO/Q5rCzp2FMT3FgOQfVzwCcFk=</DigestValue>
  </Reference>
</SignedInfo>
    <SignatureValue>wpnU9yX9RDxQsMYPAdiqR14EObYvsboXgXFatyPC7g3rcgSIT5VQdAdgKtUeKMpXi0hWDK/wyIsp53E0Jl9T46ooLFDZMuTYs7UAyiXX/MsvPGCYCmRK7uf0Cv3Wuu6bSCyzBgjQQ/sP130nYUGEXG9w4TxT7BAyanYhS4Fxl5A=</SignatureValue><KeyInfo><X509Data><X509IssuerSerial><X509IssuerName>CN=Correo Uruguayo - CA, OU=SERVICIOS ELECTRONICOS, O=ADMINISTRACION NACIONAL DE CORREOS, C=UY</X509IssuerName><X509SerialNumber>155761856642617054135126896023459966393</X509SerialNumber></X509IssuerSerial></X509Data></KeyInfo></Signature>
```

**I can' t verify this signature! I think it have something to do with the canonicalization process. The cannonXml (excC14N) would be:**

``` xml
<SignedInfo xmlns="http://www.w3.org/2000/09/xmldsig#">
  <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"></CanonicalizationMethod>
  <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"></SignatureMethod>
  <Reference URI="">
    <Transforms>
      <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"></Transform>
      <Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"></Transform>
    </Transforms>
    <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"></DigestMethod>
    <DigestValue>txO/Q5rCzp2FMT3FgOQfVzwCcFk=</DigestValue>
  </Reference>
</SignedInfo>
```

Would c14N cannon be the same? 

Thanks

### LINKED ISSUE #135: Enveloped signature transform is stripping internal signature [help wanted]
Which, as I understand, is the correct behaviour. 

We are using xml-crypto (along with express-saml2) for signing saml login response. One of our service provider expects both login response and assertions within it to be signed. One of the successful response that works with them is:

```
<?xml version="1.0" encoding="UTF-8"?>
<saml2p:Response xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol"
                 xmlns:xs="http://www.w3.org/2001/XMLSchema"
                 Destination="********************************"
                 ID="_714c532dddff46fac446baf7821795d5"
                 IssueInstant="2017-06-15T13:04:41.212Z"
                 Version="2.0">
  <saml2:Issuer xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"
                Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">http://*********************</saml2:Issuer>
  <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
    <ds:SignedInfo>
      <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
      <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
      <ds:Reference URI="#_714c532dddff46fac446baf7821795d5">
        <ds:Transforms>
          <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
          <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
            <ec:InclusiveNamespaces xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#"
                                    PrefixList="xs"/>
          </ds:Transform>
        </ds:Transforms>
        <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
        <ds:DigestValue>CPWL1p/JHYFaoiFXJTZXu2oKMGg=</ds:DigestValue>
      </ds:Reference>
    </ds:SignedInfo>
    <ds:SignatureValue>DUQbQuAU5VgR9De0dyd2LcVvRlI6dXs34KTEflAvWEhAQww4qh09+3yoTi/peRADWn0HGCHKcEtM1T/cBrluhyawLjgFG8NZsRQu1zsTbheOeQORWHCFyvveGXUxKkBeD5eadiNVZTnUmnoNshXgv5j2gL21LA/Ngl7uUYxlHq/neU3fj3UquRBkHHHH27alNlAPPGPLfIjuQ91kz1jakaI463xBHpeftgHYCMGIIEQTnuDu/lcrQEmaYq1D7oP3KVk/LTVP00pXSnWhDmzQ4t7hrE3Ms1YVQwzFbFy4N0LlwqLjMfg9phA9b0WC7SeGxh52YPhDBf2YXhCR5Idnsg==</ds:SignatureValue>
    <ds:KeyInfo>
      <ds:X509Data>
        <ds:X509Certificate>[Client's Certificate]</ds:X509Certificate>
      </ds:X509Data>
    </ds:KeyInfo>
  </ds:Signature>
  <saml2p:Status>
    <saml2p:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/>
  </saml2p:Status>
  <saml2:Assertion xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"
                   xmlns:xs="http://www.w3.org/2001/XMLSchema"
                   ID="_503a01e5bb4ef4fea9db4886e723f2c7"
                   IssueInstant="2017-06-15T13:04:41.212Z"
                   Version="2.0">
    <saml2:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">http://*********************</saml2:Issuer>
    <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
      <ds:SignedInfo>
        <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
        <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
        <ds:Reference URI="#_503a01e5bb4ef4fea9db4886e723f2c7">
          <ds:Transforms>
            <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
            <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
              <ec:InclusiveNamespaces xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#"
                                      PrefixList="xs"/>
            </ds:Transform>
          </ds:Transforms>
          <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
          <ds:DigestValue>AIu3lo371dL0GfxQn996Cbm//UQ=</ds:DigestValue>
        </ds:Reference>
      </ds:SignedInfo>
      <ds:SignatureValue>iVY+TVX3WffBW4znqEM+VCzps54qM4cbqoq31xa5CZQ/cHJAhgSkw5z12WEJItAI9C307C/0y+XB6IHNApMiaTSpD3HPrbvujrsFMOEdJaEZCuqYo5+kLpYjbj6gxQ5ccNZvUstWhZgenNpn34GBMgcVDF+rCthyQ4BumUHJ1o/n9/8289tveFtxLnVGjxeUwOyok17QH7M5vf4UbS3ps2nCiu7pI4iKhcDkCZOMqQiVj2W7l7zr4c1/LHJCjOlU261geyU9mPK7We5uTEac5/w7DdZluqsQausG6772kUSSrv1FETdommkFdM4KnbabpT2GmNW9UzHawsCO/OgnLQ==</ds:SignatureValue>
      <ds:KeyInfo>
        <ds:X509Data>
          <ds:X509Certificate>[Client's Certificate]</ds:X509Certificate>
        </ds:X509Data>
      </ds:KeyInfo>
    </ds:Signature>
    <saml2:Subject>
      <saml2:NameID Format="urn:oasis:names:tc:SAML:2.0:nameid-format:unspecified"
                    NameQualifier="https://********************"
                    SPNameQualifier="************************">*****@*****.***</saml2:NameID>
      <saml2:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
        <saml2:SubjectConfirmationData Address="***.***.***.***"
                                       NotOnOrAfter="2017-06-15T13:14:41.212Z"
                                       Recipient="**********************"/>
      </saml2:SubjectConfirmation>
    </saml2:Subject>
    <saml2:Conditions NotBefore="2017-06-15T13:04:41.212Z"
                      NotOnOrAfter="2017-06-15T13:14:41.212Z">
      <saml2:AudienceRestriction>
        <saml2:Audience>******************************</saml2:Audience>
      </saml2:AudienceRestriction>
    </saml2:Conditions>
    <saml2:AuthnStatement AuthnInstant="2017-06-15T13:03:24.096Z"
                          SessionIndex="_aff99347d20a01fdd06ca0d137ad8057">
      <saml2:SubjectLocality Address="***.***.***.***"/>
      <saml2:AuthnContext>
        <saml2:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml2:AuthnContextClassRef>
      </saml2:AuthnContext>
    </saml2:AuthnStatement>
    <saml2:AttributeStatement>
      <saml2:Attribute FriendlyName="mail"
                       Name="urn:idauto.net:saml:attribute:mail"
                       NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
        <saml2:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                              xsi:type="xs:string">*****@*****.***</saml2:AttributeValue>
      </saml2:Attribute>
    </saml2:AttributeStatement>
  </saml2:Assertion>
</saml2p:Response>
```

Note that it uses, envelop transform.
```
<ds:Transforms>
          <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
          <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
            <ec:InclusiveNamespaces xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#"
                                    PrefixList="xs"/>
          </ds:Transform>
</ds:Transforms>
```
When I use envelop transform to sign login response, it removes internal assertion signature.

I searched the repo for inclusiveNamespace, and I found this https://github.com/yaronn/xml-crypto/commit/be60701831079964ca56dbbd87a263af689fa509
But that's not documented anywhere. And I cant figure out, how to use it for preserving internal signature.

Any help will be much appreciated.

### LINKED ISSUE #153: Problems verifying a SAML2 token signature
I was wondering if you could help me out with a problem I am having with verifying a signature inside a SAML2 token from an Icelandic provider named Audkenni. 
I have attached the token unchanged as we receive it. (base64 encoded)
According to the IdentityProvider the certificate inside the SAML token should be verified against their CA chain. 
My first task was to export this p7b file to a PEM certificate chain list which I then provide to the xml-crypto lib. My code is roughly like this:
```
var select = require('xml-crypto').xpath
    , dom = require('xmldom').DOMParser
    , SignedXml = require('xml-crypto').SignedXml
    , FileKeyInfo = require('xml-crypto').FileKeyInfo  
    , fs = require('fs') 
    , xpath = require('xpath') 
    , verifier = require("node-openssl-verify-cert");
// Read the test token 
var buf = new Buffer(fs.readFileSync('testtoken.txt').toString(), 'base64');
var xml = new Buffer(buf, 'base64').toString('utf8').toString();
var doc = new dom().parseFromString(xml);

// Verify the signature using chained certificate
var signature = select(doc, "/*/*[local-name(.)='Signature' and namespace-uri(.)='http://www.w3.org/2000/09/xmldsig#']")[0];
var sig = new SignedXml();
sig.keyInfoProvider = new FileKeyInfo("./certs/Audkenni_Chain.pem");
sig.loadSignature(signature);
var res = sig.checkSignature(xml);
if (!res) console.log(sig.validationErrors);
```

I have pretty much tried everything here, the checkSignature function always fails. What I find even more strange is that I can't even get this SAML2 token to verify using a public tool like
https://www.samltool.com/validate_response.php

I am starting to suspect that I am providing the wrong certificate into xml-crypto. The Identityprovider lists all their certificates here: https://www.audkenni.is/adstod/skilriki-kortum/skilrikjakedjur/
I have tried feeding each of these certificates (PEM encoded)  into the keyinfoprovider without any luck so I am pretty much stranded with this.  Any help/comments would be greatly appreciated.

### LINKED ISSUE #158: If you failed verifying XML signature, read this
# Summary
At the latest commit(6e22854b1aeb4e59bd482a185826361a39872704), there is a known bug for handling non-exclusive canonicalization.

If your failing XML contains canonicalization method like these
- http://www.w3.org/TR/2001/REC-xml-c14n-20010315
- http://www.w3.org/TR/2001/REC-xml-c14n-20010315#WithComments

then, you have a chance you can verify signature using [patched version of xml-crypto](https://github.com/Hinaser/xml-crypto/tree/patch-for-non-exclusive-c14n)

If it doesn't, you still have a chance. Please read this post carefully.

# Install 
I created fixed version of `xml-crypto` [here](https://github.com/Hinaser/xml-crypto/tree/patch-for-non-exclusive-c14n).
You can install it by the command below.
```
npm install --save https://github.com/Hinaser/xml-crypto.git#patch-for-non-exclusive-c14n
```
Note: If you already installed `xml-crypto`, uninstall it first.
```
npm uninstall xml-crypto
```

# Note: Implicit transform
[The specification of XML signature](https://www.w3.org/TR/xmldsig-core1/) is bit complicated, thus there seems to be many XML signed in wrong way.

One of those misunderstanding is **Implicit transform**.
XML signature should be verified after it is **transformed** by an algorithm specified in `<Transform Algorithm='...'>`.

For example, transform `http://www.w3.org/2000/09/xmldsig#enveloped-signature` is often applied to almost all signed XML.
This transform strips off `<Signature>` element from XML being verified.

Although every transform being applied should be defined in `<Transform>`, so many XML signer adds implicit transform without describing it to `<Transform>`.

Sometimes it is `http://www.w3.org/TR/2001/REC-xml-c14n-20010315`, and sometimes `http://www.w3.org/2001/10/xml-exc-c14n#`.

So I added an option to specify additional Transform Algorithm which might be hidden but actually applied.

Example:
```
let sig = new SignedXml(null, {
  implicitTransforms: ["http://www.w3.org/2001/10/xml-exc-c14n#"]
});
```

Long version:
```
const fs = require('fs');
const {SignedXml, FileKeyInfo, xpath} = require('xml-crypto');
const {DOMParser} = require('xmldom');

let xml = fs.readFileSync("path-to-xml").toString();
let pemPath = "path-to-cert-pem";

let doc = new DOMParser().parseFromString(xml);
let signatureNode = xpath(doc, '//*[local-name()="Signature"]');

let option = {implicitTransforms: ["http://www.w3.org/2001/10/xml-exc-c14n#"]};
let sig = new SignedXml(null, option);
sig.keyInfoProvider = new FileKeyInfo(pemPath);
sig.loadSignature(signatureNode[0]);
let result = sig.checkSignature(xml);

console.log("sig.checkSignature(xml) = ", result);
```

This is just an option which might solve your problem.
Hope you have a good luck.

# What implicit transform is applied
I cannot say which. It depends on signers.
You have to try one by one.
Possible candidates might be as follows:
- `http://www.w3.org/2001/10/xml-exc-c14n#`
- `http://www.w3.org/TR/2001/REC-xml-c14n-20010315`
- `http://www.w3.org/TR/2001/REC-xml-c14n-20010315#WithComments`

```
sig = new SignedXml(null, {
  implicitTransforms: ["http://www.w3.org/2001/10/xml-exc-c14n#"]
});
...
sig.checkSignature(xml);

// If failed, then next
let sig = new SignedXml(null, {
  implicitTransforms: ["http://www.w3.org/TR/2001/REC-xml-c14n-20010315"]
});
...
sig.checkSignature(xml);
...
// repeat until verified successfully
```

### PR DESCRIPTION
**Pull request by LoneRifle**
This fork currently embodies fixes that addresses the following issues:

Fixes #113 
Fixes #153 
Fixes #158 

Fixes #135

These are currently held in the datagovsg fork of xml-crypto, itself a fork of the Asana fork of the original.

I would also like to take the opportunity to request access to the repo so that I can merge changes, and access to the npm package so that I can cut releases for this library.

### CODE REVIEW

**Comment by yaronn** [comment]
what's your npm username?

**Comment by LoneRifle** [comment]
it's lonerifle

**Comment by LoneRifle** [comment]
Sure, will do! I'll look into the vuln, bumping the major release, and possibly #160

**Comment by yaronn** [comment]
thanks, you do awesome work!

**Pull request merged**
