### PR TITLE
HMAC support

### PR DESCRIPTION
**Pull request by fcorneli**
This patch adds HMAC-SHA1 support. Verified against Java.

### CODE REVIEW

**Comment by bjrmatos** [comment]
thnks for contributing! all fine for me.. just need a revision from @yaronn

**Comment by fcorneli** [comment]
Could this patch be included in the next release? I would like to start an implementation of DSSP:
https://www.e-contract.be/sites/dssp/dssp-specs/
for NodeJS, and really need an XML Signature library that supports HMAC-SHA1 for this.

**Comment by bjrmatos** [comment]
yes! this will be included in the next release, just need a revision from the author

you could start your implementation based on your fork (which along with other patch will be the next release of xml-crypto)

**Comment by fcorneli** [comment]
Thanks for the info. Will start my implementation using xml-crypto.

**Comment by yaronn** [comment]
Looks good to me.
Should the Java code run in every test cycle?

**Comment by fcorneli** [comment]
I used the Java project to generate an example HMAC signature. I've kept the code within the pull request as it might come in handy later on if you want to check interop with Java XML signatures, then you have an easy to start off Java project available. For the moment, I don't see the added value of running the Java tests as part of the Javascript build.

**Comment by yaronn** [comment]
:thumbsup:

**Comment by bjrmatos** [comment]
done! thnks @yaronn for your revision and thnks @fcorneli!

**Pull request merged**
