### PR TITLE
signature validation fails if node passed to loadSignature is a Document

### PR DESCRIPTION
**Pull request by jess-sheneberger**
Includes a test that fails before the change in util.js is applied

example/example.js fails when run without this change

### CODE REVIEW

**Comment by bjrmatos** [comment]
Seems fine to me :) lets see what @yaronn have to say

I will check the example later

**Comment by yaronn** [comment]
looks good!

**Comment by bjrmatos** [comment]
i will merge when I have reviewed the example.. stay tunned :smile:

**Comment by bjrmatos** [comment]
The example started to fail when [this change](https://github.com/yaronn/xml-crypto/commit/f1a95ffd24836b6329092b0ef568ff723cb168e5#diff-e74e56dcb44165bb3bdd306d48a1fb7aL233) was introduced, this PR fix the example too because `findChilds` function in lib/utils.js is modified to handle a document node

**Comment by bjrmatos** [comment]
Merged, @yaronn the only thing left to do is publish to npm. I think a patch version (0.6.1) would be ok

**Comment by bjrmatos** [comment]
thnks @jess-sheneberger :clap:

**Comment by bjrmatos** [comment]
mmm.. i see a [weird error](https://travis-ci.org/yaronn/xml-crypto/builds/74736786) in travis when this was merged.. it's a npm installation error, seems a problem with a dependency in nodeunit

**Comment by yaronn** [comment]
@bjrmatos - what is you npm username? I will add you so you can publish directly there

**Comment by bjrmatos** [comment]
Thnks @yaronn, in npm my username is bjrmatos

**Comment by yaronn** [comment]
done!

**Comment by bjrmatos** [comment]
published in npm!

**Comment by yaronn** [comment]
Great work!

**Pull request merged**
