### PR TITLE
Added MIT license

### PR DESCRIPTION
**Pull request by eranyanay**

### CODE REVIEW

**Comment by eranyanay** [comment]
License for this library is not mentioned
I assume it is OK to MIT license it
Please approve

**Comment by bjrmatos** [comment]
@eranyanay thnks! can you add a mention to the license in the README? something like [this](https://github.com/yaronn/blessed-contrib#license)

**Comment by eranyanay** [comment]
@bjrmatos I added it to the README

**Comment by bjrmatos** [comment]
@eranyanay thnk you!

**Pull request merged**
