### PR TITLE
Accept existing xml prefixes to avoid adding to signature

### LINKED ISSUE #170: Custom KeyInfo, avoid adding empty/unneeded namespaces
I'm trying to create a custom KeyInfo. This mostly works with something like this:

```
function AssertionKeyInfo(assertionId) {
  this.getKeyInfo = function(key, prefix) {
    return `<wsse:SecurityTokenReference wsse11:TokenType="http://docs.oasis-open.org/wss/oasis-wss-saml-token-profile-1.1#SAMLV1.1" wsu:Id="STR-${uuidv4()}" 
          xmlns:wsse11="http://docs.oasis-open.org/wss/oasis-wss-wssecurity-secext-1.1.xsd">
          <wsse:KeyIdentifier ValueType="http://docs.oasis-open.org/wss/oasis-wss-saml-token-profile-1.0#SAMLAssertionID">${assertionId}</wsse:KeyIdentifier>
      </wsse:SecurityTokenReference>`;
  };
}
```

This is the result:

```
<ds:KeyInfo>
	<wsse:SecurityTokenReference wsse11:TokenType="http://docs.oasis-open.org/wss/oasis-wss-saml-token-profile-1.1#SAMLV1.1" 
		xmlns:wsu="" wsu:Id="STR-ce7f89b3-d5c0-459c-b2e7-3fd656ff7cb9" 
		xmlns:wsse11="http://docs.oasis-open.org/wss/oasis-wss-wssecurity-secext-1.1.xsd" 
		xmlns:wsse="">
		<wsse:KeyIdentifier ValueType="http://docs.oasis-open.org/wss/oasis-wss-saml-token-profile-1.0#SAMLAssertionID">_81d5fba5c807be9e9cf60c58566349b1</wsse:KeyIdentifier>
	</wsse:SecurityTokenReference>
</ds:KeyInfo>
```

The problem is that the prefix wsu and wsse is added here.
This is not needed because the namespaces are already defined outside the signature.

Is there a way to prevent adding these namespaces?

I guess this happens because the signature is parsed as a separate document?  
`var signatureDoc = new Dom().parseFromString(this.signatureXml)`

### PR DESCRIPTION
**Pull request by r03**
Not sure if this is the best way, but it does work.

This adds an extra option `existingPrefixes`.
I also added this to the README and there is a test.

Fixes #170

### CODE REVIEW

**Comment by r03** [comment]
Shouldn't Travis use a more recent node version? 0.10 and 0.12 are really old and not supported anymore.

**Comment by r03** [comment]
If I make this work on the old node version, would you accept it? I'm happy to change it then.
I now this isn't the best solution, but I couldn't think of a better one with the current xmldom.

**Comment by LoneRifle** [comment]
I would - and I was planning to make the changes in your branch if not for life getting in the way. Feel free to go ahead of me.

**Comment by r03** [comment]
It should be solved now. Thanks for maintaining this library!

**Pull request merged**
