### PR TITLE
Don't pull the example folder into the module build

### PR DESCRIPTION
**Pull request by dosullivan557**

### CODE REVIEW

**Comment by dosullivan557** [comment]
Hi @gcharnock @bergie @locnguyen @cava23 - could you review this pr please.

I install your module in an application, it copies over .pem and .key files that are in your tests. This means that when we put our application through security scans, it fails because it finds these files and classifies them as sensitive data. What I'm asking is whether you can not include these in the bundled version of the application.

To resolve it, you can have a section in the package.json that doesn't pull the test files over to the build of the module when it is pulled in.

**Comment by dosullivan557** [comment]
Resolves #221

**Comment by cava23** [comment]
I thought the package-lock.json should never be hand-modded. Is there a corresponding change to package.json you're trying to make? I don't understand the intended change based on the diff.

**Comment by dosullivan557** [comment]
The package lock has only been upversioned and it wasn't done manually, I was done using the nom version patch command.

**Comment by dosullivan557** [comment]
@cava23  if you look at the latest changes, there is a files section in the package.json that specifies which folders and files need putting into the package when installed.

**Comment by cava23** [comment]
Can you remove whitespace changes so the diff is legible?

**Comment by dosullivan557** [comment]
@cava23 Sure thing - removed whitespace

**Comment by cava23** [comment]
Sorry, looked at this a little closer and it appears this is already being attempted in the `.npmignore` file. However, I believe the trailing slash is missing. I think the right change here is to update `.npmignore` to have `test/`. See if that solves your problem. I'd rather use that than add the `files` prop to package.json since that could have a greater impact than intended.

**Comment by cava23** [comment]
You can test this with `npm pack`: https://docs.npmjs.com/cli/v6/using-npm/developers#testing-whether-your-npmignore-or-files-config-works

**Comment by dosullivan557** [comment]
Moved to .gitignore, and added example in there, which is causing an issue too. @cava23

**Comment by cava23** [comment]
Nice, I assume you meant .npmignore instead .gitignore. And this is now working as expected?

**Comment by dosullivan557** [comment]
Yeah sorry I mean .npmignore.

And yep all working as expected

**Review by cava23 — APPROVED** [review]
I would like to get approval from one other contributor as I've only made a small change to this project.

**Comment by dosullivan557** [comment]
Sounds fair enough - cheers!

**Comment by dosullivan557** [comment]
Hey @yaronn - are you able to review this pull request, please.

**Review by LoneRifle — APPROVED** [review]
lgtm

**Pull request merged**
