### PR TITLE
Update signed-xml.js

### LINKED ISSUE #72: enveloped transformation + exclusive-canonicalization
Can both algorithms work together? I'm getting a [digest mismatch error](https://github.com/yaronn/xml-crypto/blob/master/lib/signed-xml.js#L315) with the following "transforms" element:

```
<ds:Transforms>
  <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
  <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
    <xc14n:InclusiveNamespaces xmlns:xc14n="http://www.w3.org/2001/10/xml-exc-c14n#" PrefixList="xs saml xsi"/>
  </ds:Transform>
 </ds:Transforms>
```

Thanks

### PR DESCRIPTION
**Pull request by lpamlie**
fix namespace issue, fixes #72

### CODE REVIEW

**Comment by LoneRifle** [comment]
I guess this is a commit that was cherry-picked from auth0/xml-crypto@25a3d1c . Thanks for bringing this up; I'll look into this and other commits that their fork has and try to reconcile the codebases

**Comment by lpamlie** [comment]
Yes, that is correct.  We're using samlify and got the same problem.  This commit fixes the problem.

Thanks
LP


-------- Original message --------

**Comment by LoneRifle** [comment]
If it's okay with you, I will like to make a PR that merges the original commit from Auth0, which will mean that yours will be closed. I'm doing that largely to ensure that contributions from forks of this repo are accounted for when merged back here. I will give you credit for bringing this up, so hope that's okay with you.

**Comment by lpamlie** [comment]
Sure, no problem.

Thanks
LP

**Pull request merged**
