### PR TITLE
Async response for built in algo sign/verify

### PR DESCRIPTION
**Pull request by troyfactor4**
Easier async integration in other projects when using built in sign/verify algorithms

### CODE REVIEW

**Comment by troyfactor4** [comment]
Apologies for the many PR's. This should be the last one.

**Comment by LoneRifle** [comment]
@troyfactor4 - given that this library is passively maintained, I thought you might want to know that there are a couple of other libraries that provides XML Digital Signatures:
[xmldsigjs](https://github.com/PeculiarVentures/xmldsigjs) - support for XMLDSIG
[xadesjs](https://github.com/PeculiarVentures/xadesjs) - support for XAdES and XMLDSIG built on top of xmldsigjs

The READMES seem to indicate that the libraries are not production-ready, but they are already in development ofr 3 years and have v2.x releases, so perhaps it might be good to discuss whether you should use their libraries instead with @microshine

**Comment by cjbarth** [comment]
@LoneRifle is this an official recommendation? That is to say, is this library no longer adding value to the NPM ecosystem?

**Comment by LoneRifle** [comment]
That's from long ago, before you came along and did active management again!

**Comment by cjbarth** [comment]
I understand that. I'm just wondering if other libraries do what this library does, then let's work together and avoid duplicate effort.

**Pull request merged**
